/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.flume.event;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Request { 
  GET, POST  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Request\",\"namespace\":\"com.example.flume.event\",\"symbols\":[\"GET\",\"POST\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
