/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.example.crunch;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum Request { 
  GET, PUT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Request\",\"namespace\":\"com.example.crunch\",\"symbols\":[\"GET\",\"PUT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
